"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-09 21:10:17.161066
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import autotrader.journal.types

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bars",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("ts", autotrader.journal.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("o", sa.Double(), nullable=False),
        sa.Column("h", sa.Double(), nullable=False),
        sa.Column("l", sa.Double(), nullable=False),
        sa.Column("c", sa.Double(), nullable=False),
        sa.Column("v", sa.Double(), nullable=False),
        sa.PrimaryKeyConstraint("symbol", "timeframe", "ts", name=op.f("pk_bars")),
    )
    op.create_table(
        "control_state",
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_control_state")),
    )
    op.create_table(
        "equity_snapshots",
        sa.Column("ts", autotrader.journal.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("equity", autotrader.journal.types.Money(), nullable=False),
        sa.Column("cash", autotrader.journal.types.Money(), nullable=False),
        sa.Column("exposure", autotrader.journal.types.Money(), nullable=False),
        sa.Column("hwm", autotrader.journal.types.Money(), nullable=False),
        sa.Column("daily_pnl", autotrader.journal.types.Money(), nullable=False),
        sa.Column("benchmark_equity", autotrader.journal.types.Money(), nullable=True),
        sa.PrimaryKeyConstraint("ts", name=op.f("pk_equity_snapshots")),
    )
    op.create_table(
        "strategies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("yaml", sa.Text(), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column(
            "active_from", autotrader.journal.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("active_to", autotrader.journal.types.UTCDateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategies")),
        sa.UniqueConstraint("hash", name=op.f("uq_strategies_hash")),
    )
    op.create_table(
        "cycles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("signal_features", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at", autotrader.journal.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "finished_at", autotrader.journal.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("outcome", sa.String(length=16), nullable=True),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["strategy_id"], ["strategies.id"], name=op.f("fk_cycles_strategy_id_strategies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cycles")),
    )
    with op.batch_alter_table("cycles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cycles_created_at"), ["created_at"], unique=False)

    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column(
            "period_start", autotrader.journal.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "period_end", autotrader.journal.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("report", sa.JSON(), nullable=False),
        sa.Column("cost_usd", autotrader.journal.types.Money(), nullable=False),
        sa.Column("ts", autotrader.journal.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_id"], ["strategies.id"], name=op.f("fk_reviews_strategy_id_strategies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
    )
    op.create_table(
        "agent_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=True),
        sa.Column("agent", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=16), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("input", sa.JSON(), nullable=False),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("cost_usd", autotrader.journal.types.Money(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("ts", autotrader.journal.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cycle_id"], ["cycles.id"], name=op.f("fk_agent_calls_cycle_id_cycles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_calls")),
    )
    with op.batch_alter_table("agent_calls", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_calls_cycle_id"), ["cycle_id"], unique=False)

    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ts", autotrader.journal.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cycle_id"], ["cycles.id"], name=op.f("fk_events_cycle_id_cycles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_ts"), ["ts"], unique=False)

    op.create_table(
        "hypotheses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by_review_id", sa.Integer(), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("trades_n", sa.Integer(), nullable=False),
        sa.Column("win_rate", sa.Double(), nullable=True),
        sa.Column("avg_r", sa.Double(), nullable=True),
        sa.Column("p_value", sa.Double(), nullable=True),
        sa.Column(
            "promoted_at", autotrader.journal.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("retired_at", autotrader.journal.types.UTCDateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('proposed', 'active', 'retired', 'rejected')",
            name=op.f("ck_hypotheses_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_review_id"],
            ["reviews.id"],
            name=op.f("fk_hypotheses_created_by_review_id_reviews"),
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"], ["strategies.id"], name=op.f("fk_hypotheses_strategy_id_strategies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hypotheses")),
    )
    op.create_table(
        "order_intents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=False),
        sa.Column("json", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Double(), nullable=False),
        sa.Column("thesis", sa.Text(), nullable=False),
        sa.Column("strongest_counter", sa.Text(), nullable=False),
        sa.Column("learnings_applied", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cycle_id"], ["cycles.id"], name=op.f("fk_order_intents_cycle_id_cycles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_intents")),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=True),
        sa.Column("broker_order_id", sa.String(length=64), nullable=True),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("qty", autotrader.journal.types.Money(), nullable=False),
        sa.Column("limit_price", autotrader.journal.types.Money(), nullable=True),
        sa.Column("stop_price", autotrader.journal.types.Money(), nullable=True),
        sa.Column("tp_price", autotrader.journal.types.Money(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "submitted_at", autotrader.journal.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", autotrader.journal.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.CheckConstraint("mode IN ('paper', 'live')", name=op.f("ck_orders_mode")),
        sa.ForeignKeyConstraint(
            ["cycle_id"], ["cycles.id"], name=op.f("fk_orders_cycle_id_cycles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("broker_order_id", name=op.f("uq_orders_broker_order_id")),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=True),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("qty", autotrader.journal.types.Money(), nullable=False),
        sa.Column("entry_price", autotrader.journal.types.Money(), nullable=False),
        sa.Column("stop", autotrader.journal.types.Money(), nullable=True),
        sa.Column("tp", autotrader.journal.types.Money(), nullable=True),
        sa.Column(
            "time_limit_at", autotrader.journal.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("opened_at", autotrader.journal.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("closed_at", autotrader.journal.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("exit_reason", sa.String(length=32), nullable=True),
        sa.Column("realized_pnl", autotrader.journal.types.Money(), nullable=True),
        sa.Column("fees", autotrader.journal.types.Money(), nullable=True),
        sa.Column("mae", autotrader.journal.types.Money(), nullable=True),
        sa.Column("mfe", autotrader.journal.types.Money(), nullable=True),
        sa.Column("r_multiple", autotrader.journal.types.Money(), nullable=True),
        sa.Column("llm_cost_usd", autotrader.journal.types.Money(), nullable=True),
        sa.Column("benchmark_return", autotrader.journal.types.Money(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cycle_id"], ["cycles.id"], name=op.f("fk_positions_cycle_id_cycles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
    )
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_positions_closed_at"), ["closed_at"], unique=False)

    op.create_table(
        "risk_decisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cycle_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("adjusted", sa.JSON(), nullable=False),
        sa.Column("computed_size", autotrader.journal.types.Money(), nullable=True),
        sa.Column("ts", autotrader.journal.types.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('entry', 'exit')", name=op.f("ck_risk_decisions_kind")),
        sa.ForeignKeyConstraint(
            ["cycle_id"], ["cycles.id"], name=op.f("fk_risk_decisions_cycle_id_cycles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_decisions")),
    )
    op.create_table(
        "fills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("qty", autotrader.journal.types.Money(), nullable=False),
        sa.Column("price", autotrader.journal.types.Money(), nullable=False),
        sa.Column("fee", autotrader.journal.types.Money(), nullable=False),
        sa.Column("ts", autotrader.journal.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_fills_order_id_orders")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fills")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fills")
    op.drop_table("risk_decisions")
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_positions_closed_at"))

    op.drop_table("positions")
    op.drop_table("orders")
    op.drop_table("order_intents")
    op.drop_table("hypotheses")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_ts"))

    op.drop_table("events")
    with op.batch_alter_table("agent_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_calls_cycle_id"))

    op.drop_table("agent_calls")
    op.drop_table("reviews")
    with op.batch_alter_table("cycles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cycles_created_at"))

    op.drop_table("cycles")
    op.drop_table("strategies")
    op.drop_table("equity_snapshots")
    op.drop_table("control_state")
    op.drop_table("bars")
    # ### end Alembic commands ###
